ktor:
    application:
        modules:
            - party.jml.partyboi.ApplicationKt.module
    deployment:
        port: 8123
postgres:
    url: "jdbc:postgresql://localhost/partyboi"
    user: "postgres"
    password: "hunter2"
