name: "Build an image"
inputs:
  repositoryName:
    description: "Target repository name"
    required: true
    default: "ilkkahanninen/partyboi"
  tag:
    description: "Image tag"
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Build an image
      shell: bash
      run: docker build . --tag ${{ inputs.repositoryName }}:${{ inputs.tag }}
    - name: Save the image to tarball
      shell: bash
      run: docker save ${{ inputs.repositoryName }}:${{ inputs.tag }} -o partyboi.tar
    - name: Store the image
      uses: actions/upload-artifact@v4
      with:
        name: partyboi-image
        path: partyboi.tar
