name: "Build and publish the image"
inputs:
  repositoryName:
    description: "Target repository name"
    required: true
    default: "ilkkahanninen/partyboi"
  tag:
    description: "Image tag"
    required: true
    default: "latest"
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      shell: bash
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build the image
      shell: bash
      run: docker build . --tag ${{ inputs.repositoryName }}:${{ inputs.tag }}
    - name: Publish the image
      shell: bash
      run: docker push ${{ inputs.repositoryName }}:${{ inputs.tag }}
