name: Build and publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup database for tests
      run: docker compose --file docker-compose-dev.yml up db -d
    - name: Run tests
      run: gradle test
    - name: Clean up
      run: |
        docker compose --file docker-compose-dev.yml down
        sudo rm -rf data
    - name: Login to Docker Hub
      run: docker login -u ilkkahanninen -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build a release image
      run: docker build . --tag ilkkahanninen/partyboi:latest
    - name: Publish the image
      run: docker push ilkkahanninen/partyboi
