name: Pull request checks

on:
  pull_request:

jobs:
  tests:
    name: "Tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run tests
        uses: ./.github/actions/run-tests
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build an image
        uses: ./.github/actions/build-image
  publish:
    needs:
      - build
      - tests
    name: "Publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Publish the image
        uses: ./.github/actions/publish-image
        with:
          dockerPassword: ${{ secrets.DOCKER_PASSWORD }}
          dockerUsername: ${{ secrets.DOCKER_USERNAME }}