name: Build and publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: "Run tests and publish"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/run-tests
      - uses: ./.github/actions/build-and-publish
