name: Run tests

on:
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        docker compose --file docker-compose-dev.yml up db -d
        sudo mkdir -p data/test
        sudo chmod -R 777 data
        gradle test -i
